### PR TITLE
support for changing multiple sockets at once

### PR DESCRIPTION
**Pull request by drawk-cab**
Backwards compatible--just supply more arguments to switch_on or switch_off.
Also a new method set_state that allows the sockets to be controlled using a boolean value.
I guess that's 2 change recommendations, sorry. Not done a pull request before.

I haven't updated the version number, not sure what the etiquette is there. I didn't see an obvious development branch.

### CODE REVIEW

**Comment by bennuttall** [comment]
Library deprecated. See #15.

**Comment by colourcountry** [comment]
bummer. so now i have to figure out your new library which doesn't have this feature and re-implement it for the benefit of the community.

actually no, screw it, i'll keep my code to myself.

**Comment by bennuttall** [comment]
```python
> from gpiozero import Energenie
> sockets = [Energenie(i) for i in range(4)]
> [s.on() for s in sockets]
```

or:

```python
> from gpiozero import Energenie
> sockets = [Energenie(i) for i in range(4)]
> def on():
>    [s.on() for s in sockets]
> on()
```

or:

```python
> from gpiozero import Energenie
> lamp = Energenie(1)
> fan = Energenie(2)
> def on(*sockets):
>    [s.on() for s in sockets]
> on(lamp, fan)
```

@waveform80 maybe there's call for a composite Energenie device?

**Comment by waveform80** [comment]
> ... actually no, screw it, i'll keep my code to myself.

And passive aggressive over-reaction of the week goes to...

> @waveform80 maybe there's call for a composite Energenie device?

@bennuttall possibly - though I'm not sure it's *that* useful. Given the limited number of devices controllable by these sockets (i.e. 4), if someone wanted to control multiple in concert wouldn't they just control an adapter with one socket rather than waste a channel on another device? And if individual control is required we're back to separate devices anyway.

I'd also add, you could cheat and use a tuple literal too:

```python
from gpiozero import Energenie
from time import sleep

lamp = Energenie(1)
fan = Energenie(2)
lamp.on(), fan.on()
sleep(10)
lamp.on(), fan.off()
# etc. etc.
```

**Comment by bennuttall** [comment]
Fair enough.

I hadn't thought of using commas that way. Interesting but looks weird!

Alternatively, and essentially the same:

```python
lamp.on(); fan.on()
```

**Comment by colourcountry** [comment]
I'm sorry, I just hadn't tried to contribute to someone else's github before and was disappointed about not hearing anything for 15 months.

As it happens I use it because the things I want to switch on are in different rooms.
I submitted the code mainly because someone else had also requested the feature.

**Pull request closed without merging**
